spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house
    password: house
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
external:
  apartment-api:
    path: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
    service-key: qpmcpMoAZQWmgI4LRXumSAgggfp5YWAXEJfEW6TbHhbY%2BP65M03zjexeo7JH5BzXPMdxlGu9vJcD4fPfFiKjVg%3D%3D
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2