version: '3'

services:
  mysql:
    container_name: mysql_house_batch
    image: mysql/mysql-server:8.0.26
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "house"
      MYSQL_PASSWORD: "house"
      MYSQL_DATABASE: "house_batch"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci